# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-06 19:26
from __future__ import unicode_literals

from django.db import migrations
import wger.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20171122_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='time',
            field=wger.utils.fields.Html5TimeField(blank=True, null=True, verbose_name='Time (approx)'),
        ),
    ]
