# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-22 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171122_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='added_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
