# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-23 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171122_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add_user',
            field=models.BooleanField(default=False),
        ),
    ]
